[phases.setup]
nixPkgs = ["...", "bun"]

[phases.install]
# We move up to the root to run install so Bun sees the monorepo lockfile
cmds = ["cd ../.. && bun install"]

[phases.build]
cmds = ["bun run build"]

[start]
cmd = "bun run start"